### ISSUE TITLE
Include metadata in harList?

### ISSUE THREAD

**Issue by prichey** [NeuraLegion/oas2har#31]
Hi there. I think it'd be useful to (optionally) pass along the full specPath data for each operation so data like `operationId` and custom config fields would be exposed in the `harList`. Information other than the har object like description is already passed back so it'd be useful to just give back the whole object. I need to pair each spec operation with its corresponding `har` object but currently that doesn't seem to be possible without reconstructing the spec. Thanks!

**Comment by derevnjuk** [comment]
@prichey Thank you for your contribution. And sorry for the late response. I'm not sure that's useful in terms of this package. What if we add `retainOperations` flag, that allows keeping an operation alongside `har` field.

```typescript
import { Request } from 'har-format'
import { Spec, Operation } from 'swagger-schema-official'

export interface HarRequest {
  readonly operation?: Operation
  readonly har: Request
}

export function oasToHarList(
  spec: Spec | string, 
  options?: { retainOperations?: boolean }
): Promise<HarRequest[]>
```

**Comment by prichey** [comment]
That works for me! I ended up solving my particular problem using a different approach but I do think that'd be a good contribution to the library. Thanks!
