### ISSUE TITLE
Generate mock data based on the OAS spec

### ISSUE THREAD

**Issue by ArtemDerevnjuk** [NeuraLegion/oas2har#4]
For today we produce following string value, where `EXPECTED TYPE` is a type of parameter

`SOME_<EXPECTED_TYPE>_VALUE `

Instead we should put mock data with actual type

**Comment by ArtemDerevnjuk** [comment]
- [ ] implement `allOf` array
- [ ] add support of `uri template` (https://swagger.io/docs/specification/serialization/)
- [ ] add support `application/x-www-form-urlencoded` and `image/*`  media types in `requestBody` (https://swagger.io/docs/specification/media-types/)

**Comment by bararchy** [comment]
Sounds great, that would really help ensure we attack the right things with passable data structure and format.

I would prioritize basic types first, and then start extending support.

**Comment by ArtemDerevnjuk** [comment]
@bararchy we have added support of basic types and formats. Can we start to working on it?

**Comment by bararchy** [comment]
Let's do it! @ArtemDerevnjuk
